import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from "@mui/material/Button";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          I am Saad Al Muttakee. Web developer, football freak, love to sleep, watched too many sitcoms.
          I am currently working at Enosis Solutions.
          I also have experience of working with React, Django, NodeJS.
          Interested in blockchain, system design and backend architecture.

          <br />
        </p>
      <div>
          About
          You can contact me via --
          <a href="mailto:muttakee9@gmail.com">
              <img alt="Gmail" target="_blank" width="22px" src="https://cdn.worldvectorlogo.com/logos/official-gmail-icon-2020-.svg" />
          </a>
          <a href="https://www.linkedin.com/in/saad-al-muttakee-5aa399158/">
              <img alt="LinkedIn" target="_blank" width="22px" src="https://cdn4.iconfinder.com/data/icons/social-messaging-ui-color-shapes-2-free/128/social-linkedin-circle-512.png" />
          </a>
          <a href="https://www.facebook.com/muttakee9/">
              <img alt="Facebook" target="_blank" width="22px" src="https://i.pinimg.com/originals/af/9c/cb/af9ccb82cd058e86d5a487223980e31c.png" />
          </a>
          <a href="https://www.twitter.com/muttakee31/">
              <img alt="Twitter" target="_blank" width="22px" src="https://i.pinimg.com/originals/af/9c/cb/af9ccb82cd058e86d5a487223980e31c.png" />
          </a>
          <a href="https://www.github.com/muttakee11/">
              <img alt="Github" target="_blank" width="22px" src="https://i.pinimg.com/originals/af/9c/cb/af9ccb82cd058e86d5a487223980e31c.png" />
          </a>
      </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
