import type {NextPage} from 'next'
import Head from 'next/head'
import img from 'next/img'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          I am Saad Al Muttakee. Web developer, football freak, love to sleep, watched too many sitcoms.
          I am currently working at Enosis Solutions.
          I also have experience of working with React, Django, NodeJS.
          Interested in blockchain, system design and backend architecture.

          <br />
        </p>
      <div>
          You can find me here --
          <br />
          <a href="https://www.github.com/muttakee11/">
              <img src="https://img.icons8.com/ios-glyphs/48/000000/github.png" alt="GitHub"/>
          </a>
          <a href="mailto:muttakee9@gmail.com">
              <img src="https://img.icons8.com/color/48/000000/gmail-new.png" alt="Gmail"/>
          </a>
          <a href="https://www.linkedin.com/in/saad-al-muttakee-5aa399158/">
              <img src="https://img.icons8.com/color/48/000000/linkedin.png" alt="Linkedin"/>
          </a>
          <a href="https://www.facebook.com/muttakee9/">
              <img src="https://img.icons8.com/color/48/000000/facebook-new.png" alt="facebook"/>
          </a>
          <a href="https://www.twitter.com/muttakee31/">
              <img src="https://img.icons8.com/fluency/48/000000/twitter.png" alt="Twitter"/>
          </a>

      </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
